
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// El propio schema.prisma resuelve `env("DATABASE_URL")` leyendo
// process.env directamente (independiente de datasource.url de abajo),
// así que sin esto la validación del schema revienta el build apenas
// falta la variable, aunque `generate` no necesite una conexión real.
process.env.DATABASE_URL ??= "file:./prisma/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
